
export const FETCH_MEMBERS_REQUEST= 'FETCH_MEMBERS_REQUEST';
export const FETCH_MEMBERS_SUCCESS='FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_FAIL='FETCH_MEMBERS_FAIL';
export const POST_SUCCESS='POST_SUCCESS';
export const POST_FAIL='POST_FAIL';